language: crystal

crystal:
  - latest
  - nightly

install:
  - shards install

script:
  - crystal spec
  - crystal bin/ameba.cr
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: docs
