name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: latest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Generate
        run: crystal docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs